USE db_escola_M;

--IRÁ EXIBIR SOMENTE AS COLUNAS PAERSONALIZADAS(DIFERENTES DO *)
SELECT id, nome FROM tb_escola;

--SELECT TOP LIMITA A QUANTIDADE DE REGISTROS
SELECT TOP 3 nome FROM tb_aluno;

--EXEBIR SOMENTE 3 REGISTROS DO MAIS RECENTE PARA O MENOS RECENTE
SELECT TOP 3 nome 
FROM tb_aluno
ORDER BY id DESC;

--EXIBE SOMENTE O NOME DA TURMA DO PERIODO DA MANHÃ
SELECT * FROM tb_turma

SELECT nome_turma
FROM tb_turma
WHERE periodo = 'Manhã';

--EXIBE A PROVA DA PROFESSORA janaina
SELECT * FROM tb_prova
WHERE nome_professor = 'janaina';

--EXIBE QUANTOS ALUNOS TEM
SELECT COUNT(cpf) AS qtd_total_aluno FROM tb_aluno;

--EXIBE QUANTOS ALUNOS ESTÃO ATRELADOS A PROVA QUE PERTENCE A UMA MATERIA
SELECT COUNT(id_aluno) AS qta_alunos
FROM tb_prova
WHERE materia = 'Geografia';

--EXIBE A DATA DE NASCIMENTO MAIS VELHA
SELECT MIN(data_nasc) FROM tb_aluno;

--EXIBE A DATA DE NASCIMENTO MAIS NOVA
SELECT MAX(data_nasc) FROM tb_aluno;

--2000 - MAX(MAIOR)
--1970 - MIN(MENOR)

--EXIBE A DATA DE NASCIMENTO E O NOME DO ALUNO MAIS VELHO
SELECT nome, data_nasc
FROM tb_aluno
WHERE data_nasc = (SELECT MIN(data_nasc) FROM tb_aluno);


--SOMA OS ID's DAS TURMAS CADASTRADAS
SELECT SUM(id) FROM tb_turma;

--MEDIA DE NOTAS DE PROVA
SELECT AVG(NOTA) AS MEDIA FROM tb_prova;

--EXIBE OS ID's E A DATA DE NASCIMENTO DOS MAIS NOVOS
SELECT MAX(data_Nasc) AS mais_novo, id
FROM tb_aluno
GROUP BY id
ORDER BY mais_novo DESC;
